version: '3'

services:
  message-service:
    image: registry.cn-beijing.aliyuncs.com/kuone/message-service:lastest

  user-service:
    image: registry.cn-beijing.aliyuncs.com/kuone/user-service:lastest
    command:
    - "--mysql.address=192.168.0.13"

  user-edge-service:
    image: registry.cn-beijing.aliyuncs.com/kuone/user-edge-service:lastest
    links:
    - user-service
    - message-service
    command:
    - "--redis.address=192.168.0.13"

  course-service:
    image: registry.cn-beijing.aliyuncs.com/kuone/course-service:lastest
    links:
    - user-service
    - message-service
    command:
    - "--mysql.address=192.168.0.13"
    - "--zk.address=192.168.0.13"

  course-edge-service:
    image: registry.cn-beijing.aliyuncs.com/kuone/course-edge-service:lastest
    links:
    - user-edge-service
    command:
    - "--zk.address=192.168.0.13"

  api-gateway-zuul:
    image: registry.cn-beijing.aliyuncs.com/kuone/api-gateway-zuul:lastest
    links:
    - user-edge-service
    - course-edge-service
    ports:
    - 8080:8080